language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN="
install:
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
